### ISSUE TITLE
Enhancement: solo button for readers?

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#62] opened 2017-03-27 14:51 UTC
especially now that the interface is (nicely) cluttered with spawners

**Comment by dhowe** [comment] 2017-03-27 15:35
yes, just wanted to get your opinion first (thus the assignment) -- sally, any thoughts on a design here?

**Comment by cqx931** [comment] 2017-03-28 03:52
How about adding a clickable 's' button before the circle?
The button should only be visible if an reader is active.
If the solo button is clicked. All other readers would be greyed out and show no interaction.
Once the solo mode is turned off, readers that were previously active would come back.

![image](https://cloud.githubusercontent.com/assets/3056154/24388326/887d507e-13ac-11e7-8e66-cd8c2d2be987.png)
![image](https://cloud.githubusercontent.com/assets/3056154/24388330/8b73c7cc-13ac-11e7-8ae1-5d0723ca3935.png)

**Comment by dhowe** [comment] 2017-03-28 04:24
Sounds good to me -- @shadoof ?
(just an idea, but with this design [which does resemble audio software] , we might also consider an F for focus)

**Comment by dhowe** [comment] 2017-03-29 10:56
what about something like this?

![image](https://cloud.githubusercontent.com/assets/737638/24451452/6f1b786c-14b1-11e7-868c-2faaec97ff1b.png)

**Comment by dhowe** [comment] 2017-03-29 10:57
Note also, that maybe we don't need to say 'reader' over and over... instead we might, for example, have:

- Perigram Reader
- Mesostic Reader
- Oblique Perigrammer
- Simple Spawner
- Perigram Spawner

?

**Comment by dhowe** [comment] 2017-03-29 11:02
Note also, that maybe we don't need to say 'reader' over and over... instead we might, for example, have:

- Perigram Reader
- Mesostic Reader
- Abstract Perigrammer
- Simple Spawner
- Perigram Spawner

?

**Comment by shadoof** [comment] 2017-03-29 11:15
@cqx931 - I agree with @dhowe comments and proposals above, except for 'Abstract'. Suggest: 'Errant Perigram Reader'.

**Comment by dhowe** [comment] 2017-03-29 12:38
'Errant Perigrammer', or you prefer the long name?

**Comment by dhowe** [comment] 2017-05-21 11:00
@cqx931 bumping priority on 'solo' button

**Comment by cqx931** [comment] 2017-05-23 06:53
Can this be closed now?

**Comment by dhowe** [comment] 2017-05-23 06:57
need to check

**Comment by dhowe** [comment] 2017-05-24 07:38
Bug: One reader must always have focus (this doesn't happen on page load)

**Comment by dhowe** [comment] 2017-05-24 07:43
Note: solo should gray-out the other boxes, not make them disappear

**Comment by dhowe** [comment] 2017-05-24 07:45
Console error:

![image](https://cloud.githubusercontent.com/assets/737638/26392086/ee348ae6-4097-11e7-9c71-38c7af9612f4.png)

**Comment by dhowe** [comment] 2017-05-24 07:49
Bug: it is possible to get two (or more) readers to have 'solo' at the same time, which is incorrect:

![image](https://cloud.githubusercontent.com/assets/737638/26391980/7f4fbd94-4097-11e7-8480-96818e39cae9.png)

**Comment by cqx931** [comment] 2017-05-24 08:57
I think it is necessary to keep the outline to tell the difference between a button and a select.

**Comment by cqx931** [comment] 2017-05-24 09:08
> Console error (when switching to another tab and back)
This is not related to this ticket, but it is caused by the following line. Why themeChanged() is called when switching back to the readersJS page?
https://github.com/dhowe/ReadersJS/blob/master/src/multi-page-ui.js#L404

**Comment by dhowe** [comment] 2017-05-24 11:06
`visually: lets try a) removing the stroke-outline on those buttons, and b) only graying them out when a reader has solo, not removing them altogether`

1. the strokes on the squares are still there
2. I meant that the other solo/focus and speed buttons should be grayed when they are not active

![image](https://cloud.githubusercontent.com/assets/737638/26400530/ef95c17c-40b3-11e7-8681-8c91e6f44311.png)

**Comment by cqx931** [comment] 2017-05-24 13:44
Here is the tweak: https://github.com/dhowe/ReadersJS/pull/134
But I think it is necessary to have different styles for a button and a select...

**Comment by dhowe** [comment] 2017-05-24 15:02
might also consider making them round

**Comment by cqx931** [comment] 2017-05-25 02:20
1.Is this faint enough? (30% opacity)
![image](https://cloud.githubusercontent.com/assets/3056154/26433107/29791360-4133-11e7-8085-88c5035c4186.png)

2.Not sure about the color here. In sound editing softwares, the control panel for each track doesn't have any representing color, so the color of each button has a unique correlation within the control panel. But here it might conflict with the color of a reader... (red/yellow/orange) 
Also in widely used conventions, these buttons have stroke outline border :)

3.I prefer to keep them in rectangle. Also for the border-radius, it's better to keep them all in the same style, rather use that as a style hint to differentiate between functions.

**Comment by dhowe** [comment] 2017-05-25 04:12
1. No, they should be barely visible

![image](https://cloud.githubusercontent.com/assets/737638/26435669/762b7c6a-4143-11e7-8dad-3c1b88004b77.png)

**Comment by dhowe** [comment] 2017-05-25 04:18
1. Getting close -- they should be barely visible (perhaps the text, steady/S/F, should have less opacity than the square?)
2. Perhaps we can use some non-color (or white?) indicator that a button is pressed. I feel like these buttons should have a uniform appearance. In a DAW, you can generally give a color to each track, but this does NOT affect the color of the buttons for that track. 
3. Two other options: a) make them a bit smaller, and/or b) use rounded rects, as in the DAW image above

**Comment by cqx931** [comment] 2017-05-25 05:05
Less visible text and non-color:
How about adding some visual hint for select instead?
![image](https://cloud.githubusercontent.com/assets/3056154/26436668/b0591ea4-414a-11e7-8907-f6cba2a44d1f.png)
![image](https://cloud.githubusercontent.com/assets/3056154/26436673/ba0e969a-414a-11e7-9de4-e3d10cc5dec5.png)

**Comment by dhowe** [comment] 2017-05-25 05:18
This makes more sense to me (and I like the little arrows for the menus). However the visual weight of Speed/S/F is still too heavy for me. As I say above, these buttons should not draw the attention away from the Reader Names/colors. 

Things to try:
-- dont use bold/different font for menu
-- reduce height of these elements by a few pixels (S/F are taller than wide)
-- smaller/light font ?

> How about adding some visual hint for select instead?
not sure what you mean here?

@shadoof pls jump-in if you have opinions

**Comment by cqx931** [comment] 2017-05-25 06:50
How about this:
![image](https://cloud.githubusercontent.com/assets/3056154/26439129/461fba3e-4159-11e7-9084-203a004ff9a4.png)

**Comment by shadoof** [comment] 2017-05-25 14:28
Looking pretty good to me now, but checking two things here:
* We are giving up on double-clicking the circle to set focus? (I think, yes: using the S and F buttons *is* better)
* When solo (and thus focus) is set for one reader, I think it would be better to be able simply to be able to click another reader's 'S' button and give this other reader solo and focus. (At the moment you have to (un-)click the 'S' of the current solo reader and then click the 'S' of the reader you'd like to solo.

**Comment by dhowe** [comment] 2017-05-25 16:49
I agree

**Comment by dhowe** [comment] 2017-05-28 15:08
I think that clicking on any part of another reader (either their circles, names, or F/S/speed buttons) should disable the solo on another reader

**Comment by cqx931** [comment] 2017-06-07 04:21
close this one, remaining issues go to: https://github.com/dhowe/ReadersJS/issues/145

**Closed by cqx931** 2017-06-07 04:21 UTC
Labels: enhancement, priority: Med
